nelmio_api_doc:
  documentation:
    info:
      title: Cabin Booking API
      description: REST API для бронирования домиков.
      version: 1.0.0
    components:
      securitySchemes:
        bearerAuth:
          type: http
          scheme: bearer
          bearerFormat: token
  areas:
    default:
      path_patterns:
        - ^/cabins
        - ^/bookings
        - ^/login$
        - ^/logout$
        - ^/users$
        - ^/api/docs
