services:
  php:
    build: ./docker/php
    environment:
      APP_ENV: ${APP_ENV}
      DEFAULT_URI: ${DEFAULT_URI}
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    build: ./docker/nginx
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    restart: unless-stopped

  db:
    build: ./docker/db
    env_file:
      - .env.docker.local
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
