server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files \ /index.php\\;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass php:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME \\;
        fastcgi_param DOCUMENT_ROOT \;
        internal;
    }

    location ~ \.php$ {
        return 404;
    }
}
